version: '3.7'

networks:
  app-tier:

services:
  ironfish:
    build:
      context: ironfish/image
      dockerfile: ./Dockerfile
    image: ironfish-app
    restart: always
    stdin_open: true 
    tty: true
    network_mode: host
    volumes:
      - ./ironfish/data:/root/.ironfish

  prometheus:
    image: prom/prometheus
    restart: always
    volumes:
      - ./prometheus/config/prometheus:/etc/prometheus
      - ./prometheus/data:/prometheus
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    links:
      - alertmanager:alertmanager
    networks:
      - app-tier

  alertmanager:
    image: prom/alertmanager
    restart: always
    ports:
      - 9093:9093
    volumes:
      - ./prometheus/config/alertmanager:/etc/alertmanager
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
    depends_on:
      - prometheus
    networks:
      - app-tier     

  grafana:
    image: grafana/grafana-enterprise
    restart: always
    user: "472"
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - ./grafana/data:/var/lib/grafana
      - ./graphana/config/provisioning/:/etc/grafana/provisioning/
      - ./graphana/config/grafana.ini:/etc/grafana/grafana.ini
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - ./graphana/config/config.monitoring
    networks:
      - app-tier
 