version: '3.7'

networks:
  app-tier:

volumes:
  data_prometheus: 
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './../data/prometheus'

  data_grafana: 
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './../data/grafana'

services:
  ironfish_node:
    build:
      context: ironfish
      dockerfile: ./Dockerfile
    image: ironfish-app
    restart: always
    volumes:
      - ./../data/ironfish:/root/.ironfish
    ports:
      - 8020:8020
      - 9033:9033
      - 22:22
    networks:
      - app-tier


  prometheus:
    image: prom/prometheus
    restart: always
    volumes:
      - data_prometheus:/prometheus
      - ./prometheus/config/prometheus:/etc/prometheus
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    links:
      - alertmanager:alertmanager
    ports:
      - 9090:9090
    networks:
      - app-tier


  alertmanager:
    image: prom/alertmanager
    restart: always
    volumes:
      - ./prometheus/config/alertmanager:/etc/alertmanager
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
    ports:
      - 9093:9093
    networks:
      - app-tier     


  grafana:
    image: grafana/grafana-enterprise
    restart: always
    user: "472"
    volumes:
      - data_grafana:/var/lib/grafana
      - ./grafana/config/provisioning/:/etc/grafana/provisioning/
      - ./grafana/config/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/plugins:/var/lib/grafana/plugins
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - ./grafana/config/config.monitoring
    ports:
      - 3000:3000
    networks:
      - app-tier
 