{
 "title": "System Stats",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "System Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "HDD Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "system_disk_utilization", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Network In",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "system_network_input", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Network Out",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 7, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "system_network_output", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 1 },
   "targets": [
    { "expr": "system_cpu_utilization", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Memory Usage (%)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "system_memory_utilization", "legendFormat": "__auto" }
   ]
  },
  { "title": "Ironfish Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "CPU Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    { "expr": "ironfish_cpu_utilization", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Jobs/Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "ironfish_workers_jobs_per_second",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mined",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ironfish_mining_mined", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "P2P In",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 2, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ironfish_p2p_input", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "P2P Out",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 6, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ironfish_p2p_output", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "P2P Peers",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 10, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ironfish_p2p_peers", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Mem Pool / Count",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 18 },
   "targets": [
    { "expr": "ironfish_mem_pool_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Miners",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ironfish_mining_miners", "legendFormat": "__auto" }
   ]
  }
 ]
}