#!/bin/bash

IRONFISH_HOME=/nodes/ironfish

sudo mkdir -p $IRONFISH_HOME/data/grafana
sudo mkdir -p $IRONFISH_HOME/data/prometheus
sudo mkdir -p $IRONFISH_HOME/data/ironfish

sudo docker compose -f $IRONFISH_HOME/irnfbundle/docker-compose.yml up -d